// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: proto/docverify/v1/docverify.proto

package docverifyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocVerify_Submit_FullMethodName = "/docverify.v1.DocVerify/Submit"
	DocVerify_Get_FullMethodName    = "/docverify.v1.DocVerify/Get"
	DocVerify_List_FullMethodName   = "/docverify.v1.DocVerify/List"
	DocVerify_Verify_FullMethodName = "/docverify.v1.DocVerify/Verify"
	DocVerify_Delete_FullMethodName = "/docverify.v1.DocVerify/Delete"
)

// DocVerifyClient is the client API for DocVerify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DocVerify exposes document verification operations over gRPC.
// The same domain logic is served over REST by the HTTP API.
type DocVerifyClient interface {
	// Submit queues a document for verification and returns its record.
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*Document, error)
	// Get returns a single document by id.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Document, error)
	// List returns documents, optionally filtered by status.
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Verify runs the verification scoring routine on a stored document.
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*Document, error)
	// Delete removes a document by id.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type docVerifyClient struct {
	cc grpc.ClientConnInterface
}

func NewDocVerifyClient(cc grpc.ClientConnInterface) DocVerifyClient {
	return &docVerifyClient{cc}
}

func (c *docVerifyClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocVerify_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docVerifyClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocVerify_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docVerifyClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, DocVerify_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docVerifyClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocVerify_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docVerifyClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, DocVerify_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocVerifyServer is the server API for DocVerify service.
// All implementations must embed UnimplementedDocVerifyServer
// for forward compatibility.
//
// DocVerify exposes document verification operations over gRPC.
// The same domain logic is served over REST by the HTTP API.
type DocVerifyServer interface {
	// Submit queues a document for verification and returns its record.
	Submit(context.Context, *SubmitRequest) (*Document, error)
	// Get returns a single document by id.
	Get(context.Context, *GetRequest) (*Document, error)
	// List returns documents, optionally filtered by status.
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Verify runs the verification scoring routine on a stored document.
	Verify(context.Context, *VerifyRequest) (*Document, error)
	// Delete removes a document by id.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedDocVerifyServer()
}

// UnimplementedDocVerifyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocVerifyServer struct{}

func (UnimplementedDocVerifyServer) Submit(context.Context, *SubmitRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedDocVerifyServer) Get(context.Context, *GetRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDocVerifyServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDocVerifyServer) Verify(context.Context, *VerifyRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedDocVerifyServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDocVerifyServer) mustEmbedUnimplementedDocVerifyServer() {}
func (UnimplementedDocVerifyServer) testEmbeddedByValue()                   {}

// UnsafeDocVerifyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocVerifyServer will
// result in compilation errors.
type UnsafeDocVerifyServer interface {
	mustEmbedUnimplementedDocVerifyServer()
}

func RegisterDocVerifyServer(s grpc.ServiceRegistrar, srv DocVerifyServer) {
	// If the following call pancis, it indicates UnimplementedDocVerifyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocVerify_ServiceDesc, srv)
}

func _DocVerify_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocVerifyServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocVerify_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocVerifyServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocVerify_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocVerifyServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocVerify_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocVerifyServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocVerify_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocVerifyServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocVerify_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocVerifyServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocVerify_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocVerifyServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocVerify_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocVerifyServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocVerify_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocVerifyServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocVerify_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocVerifyServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocVerify_ServiceDesc is the grpc.ServiceDesc for DocVerify service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocVerify_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "docverify.v1.DocVerify",
	HandlerType: (*DocVerifyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _DocVerify_Submit_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DocVerify_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DocVerify_List_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _DocVerify_Verify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DocVerify_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/docverify/v1/docverify.proto",
}
